### ISSUE TITLE
Singleton trouble... 

### ISSUE THREAD

**Issue by rlam3** [limlab/SwiftEd#1]
Very good tutorial but got some errors when doing singletons

I keep getting `fatal error: unexpectedly found nil while unwrapping an Optional value
` when I try to do the singleton way... is there something I have to set in info plist? 

Thanks!

**Comment by fewlinesofcode** [comment]
@rlam3, thanks for mentioning! I'm in the process of updating articles for Swift 3, will fix this issue asap.

**Comment by rlam3** [comment]
@limlab Thanks for quick reply! I happen to stumble upon another issue. Because I'm already using cocoapods in my original scheme `MyApp` and when I change to `Development` Scheme... I get an error saying that: `There is no such module xxx` Could you please shed some light on this matter?

Also, how would the deployment process work? Would I have to be in the `Production` Scheme to deploy etc... ? And would this work with fastlane? https://fastlane.tools/ 

Thanks! Greatly appreciate your help!

**Comment by fewlinesofcode** [comment]
@rlam3, so, the problem was not in a Singleton, the problem was that i did not share schemes. My bad. They should be present now. Fastlane should work fine, i use it in my projects and it works fine. 

Also i recommend you just to follow the steps from article and setup each scheme by yourself. Remember to doublecheck  if you followed the step from fig. 6 in the article.

Considering to cocoapods problem: there can be some issues not related to schemes. For instance, if xcodeproj`but using`.xcworkspace`.

**Comment by rlam3** [comment]
@limlab Thanks for sharing. 

Got the code to work but...

Back to the cocoapods question. When you talk about xcodeproj but using .xcworkspace ... I've been using workspace as cocoapods suggest. is there something wrong with the process of doing it this way? Could you please be a bit more specific on what the issue is? Thanks!

**Comment by fewlinesofcode** [comment]
@rlam3 reasons may be different. Not a long time ago pods became target-specific. Podfile looks like 
'target \' YourTargetName\' do
  #your pods list
end'
Probably you made mistake in target while configured your schemes, so it can be a reason. Check your podfile and your schemes targets.

**Comment by rlam3** [comment]
@limlab 

Following your example and using the current version of your git repo for this project..
I'm using Xcode 8 and swift 3

I did the following: `pod init` 
The Podfile looks as follows: 

``` ruby

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MultiEnvSample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire','~> 4.0'

  # Pods for MultiEnvSample

  target 'MultiEnvSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultiEnvSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

Is this the way that you are referring to? If not, please provide me with some insight. Thanks!

**Comment by fewlinesofcode** [comment]
it should look like
`target 'MultiEnvSample' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'Alamofire','~> 4.0'

end

# Pods for MultiEnvSample

target 'MultiEnvSampleTests' do
    inherit! :search_paths
    # Pods for testing
end

target 'MultiEnvSampleUITests' do
    inherit! :search_paths
    # Pods for testing
end`

Try do fix podfile and update pods
