### ISSUE TITLE
How do we configure for testing?

### ISSUE THREAD

**Issue by rlam3** [limlab/SwiftEd#2]
@limlab How do we configure for using the process for testing?

I'm trying to integrate quick and nimble but have some trouble understanding why my pods are not recognized by xcode and build scheme.

I'm running into a No such Module 'Quick' I try to run tests. 

Would love your insight on this matter on how to properly configure Xcode's build scheme to make this work.

**Comment by fewlinesofcode** [comment]
Once again =) You should properly configure your Podfile (i mean create separate record for each target and import needed pods in the test target)
