### ISSUE TITLE
Were you able to configure fastlane to properly deploy to crashalytics beta?

### ISSUE THREAD

**Issue by rlam3** [limlab/SwiftEd#3]
@limlab  Were you able to configure fastlane to properly deploy to crashalytics beta?

I'm having difficulty getting this to work. 

Say we want to deploy a beta version. Should we be using the production scheme? Or should we still be using the Development scheme? 

Also, would we be using the export_method of "ad_hoc" or "development"? Thanks!

**Comment by fewlinesofcode** [comment]
It depends on your project needs. My beta releases uses production environment. Sorry, but i cannot see difficulties with it. This is just a scheme, and the purpose of the article was to tell about one of many ways to simplify work with different environments. Concrete implementation depends on project needs.
